# Generated by Django 2.0.2 on 2019-02-28 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publish_date', models.DateField(default=datetime.datetime.today)),
                ('image', models.ImageField(upload_to='images/')),
                ('details', models.TextField()),
            ],
        ),
    ]
